# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'IOSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SwiftChart'
  pod 'Nikka'
  # Pods for IOSApp

  target 'IOSAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOSAppUITests' do
    inherit! :complete
    pod 'SwiftChart'
    pod 'Nikka'
    # Pods for testing
  end

end
